apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  labels:
    app: back-app
  namespace: default
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend-app=blockcloud.kr.ncr.ntruss.com/blockcloud/backend-app
    argocd-image-updater.argoproj.io/backend-app.update-strategy: latest
    argocd-image-updater.argoproj.io/backend-app.allow-tags: 'regexp:^[0-9a-f]{7,40}$'
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/backend-app.pullsecret: ncr-image-pull-secret
    argocd-image-updater.argoproj.io/git-login-secret: argocd-git-secret
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-app
  template:
    metadata:
      labels:
        app: back-app
    spec:
      imagePullSecrets:
        - name: ncr-registry-secret
      nodeSelector:
        app-pool: front-back-nodes
      containers:
        - name: back-container
          # Image Updater가 이 태그(bdeef8...)를 최신 태그로 업데이트합니다.
          image: blockcloud.kr.ncr.ntruss.com/blockcloud/backend-app:5d0511b07fa4ef8fab9e01caea5fbaa52682c38d
          ports:
            - containerPort: 8080
