apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-app
  template:
    metadata:
      labels:
        app: front-app
    spec:
      imagePullSecrets:
        - name: ncr-registry-secret
      nodeSelector:
        app-pool: front-back-nodes
      containers:
        - name: front-container
          # Image Updater가 이 태그(de640f...)를 최신 태그로 업데이트합니다.
          image: blockcloud.kr.ncr.ntruss.com/blockcloud/frontend-app:2277ce947566d19526b67d3801a1ad9d6fc89c9f
          ports:
            - containerPort: 80
