apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-app
  template:
    metadata:
      labels:
        app: front-app
    spec:      
      nodeSelector:
        app-pool: front-back-nodes 
      
      containers:
        - name: front-container
          image: blockcloud.kr.ncr.ntruss.com/blockcloud/frontend-app:latest
          ports:
            - containerPort: 80
