apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-traffic-router
  annotations:
    kubernetes.io/ingress.class: "nginx" # NKS Ingress Controller 지정
  namespace: default
spec:
  rules:
    - host: "blockcloud.dev"
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: back-service 
                port:
                  number: 8080
          - path: /token
            pathType: Exact
            backend:
              service:
                name: back-service 
                port:
                  number: 8080
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: back-service 
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-service 
                port:
                  number: 80
