apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-traffic-router
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx" 
    cert-manager.io/cluster-issuer: "letsencrypt-prod-issuer" 
spec:
  rules:
    - host: "blockcloud.dev"
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: back-service
                port:
                  number: 8080
          - path: /token
            pathType: Exact
            backend:
              service:
                name: back-service
                port:
                  number: 8080
          - path: /login/oauth2
            pathType: Prefix
            backend:
              service:
                name: back-service
                port:
                  number: 8080                  
          - path: /oauth2/authorization
            pathType: Prefix
            backend:
              service:
                name: back-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-service
                port:
                  number: 80
  tls:
    - hosts:
        - blockcloud.dev
      secretName: blockcloud-prod-tls
